local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

local_test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials[:production][:amazon][:access_key_id]%>
  secret_access_key: <%= Rails.application.credentials[:production][:amazon][:secret_access_key] %>
  region: us-east-1
  bucket: <%= Rails.application.credentials[:production][:amazon][:bucket]%>
